/**
 * Module Test Data
 *
 * Comprehensive tests for each module in the astrology certification program.
 * Each test has 10-15 questions covering key concepts from the module.
 */

import type { ModuleTest } from '@/types/learning'

export const MODULE_TESTS: Record<string, ModuleTest> = {
  // Module 1: Foundations of Astrology
  'zodiac-basics': {
    id: 'test-foundations',
    title: 'Foundations of Astrology Test',
    description: 'Test your understanding of the fundamental building blocks of astrology.',
    passingScore: 70,
    estimatedMinutes: 15,
    questions: [
      {
        id: 'f1',
        question: 'How many signs make up the zodiac?',
        type: 'multiple-choice',
        options: ['10', '12', '13', '24'],
        correctIndices: [1],
        explanation: 'The zodiac is divided into 12 equal parts of 30° each, creating the 12 zodiac signs we know today.',
        points: 1,
      },
      {
        id: 'f2',
        question: 'What does the ecliptic represent in astrology?',
        type: 'multiple-choice',
        options: [
          'The path of the Moon around Earth',
          'The apparent path of the Sun across the sky',
          'The orbit of Jupiter',
          'The axis of Earth\'s rotation',
        ],
        correctIndices: [1],
        explanation: 'The ecliptic is the apparent path the Sun traces across the sky throughout the year, and the zodiac follows this path.',
        points: 1,
      },
      {
        id: 'f3',
        question: 'Which of the following are Fire signs?',
        type: 'multiple-select',
        options: ['Aries', 'Taurus', 'Leo', 'Sagittarius', 'Capricorn'],
        correctIndices: [0, 2, 3],
        explanation: 'Aries, Leo, and Sagittarius are the three Fire signs, known for their passion, energy, and action-oriented nature.',
        points: 2,
      },
      {
        id: 'f4',
        question: 'The Sun sign represents your core identity and life purpose.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [0],
        explanation: 'The Sun sign represents your ego, core identity, and the essential qualities you\'re developing in this lifetime.',
        points: 1,
      },
      {
        id: 'f5',
        question: 'What element is associated with practical, grounded energy?',
        type: 'multiple-choice',
        options: ['Fire', 'Earth', 'Air', 'Water'],
        correctIndices: [1],
        explanation: 'Earth signs (Taurus, Virgo, Capricorn) are associated with practical, grounded, and stable energy.',
        points: 1,
      },
      {
        id: 'f6',
        question: 'Which modality is associated with initiating and starting new things?',
        type: 'multiple-choice',
        options: ['Cardinal', 'Fixed', 'Mutable', 'Elemental'],
        correctIndices: [0],
        explanation: 'Cardinal signs (Aries, Cancer, Libra, Capricorn) are initiators who start new cycles and projects.',
        points: 1,
      },
      {
        id: 'f7',
        question: 'Select all Water signs:',
        type: 'multiple-select',
        options: ['Cancer', 'Scorpio', 'Aquarius', 'Pisces', 'Libra'],
        correctIndices: [0, 1, 3],
        explanation: 'Cancer, Scorpio, and Pisces are the Water signs. Aquarius, despite its name, is an Air sign.',
        points: 2,
      },
      {
        id: 'f8',
        question: 'A birth chart captures the positions of celestial bodies at your moment of birth.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [0],
        explanation: 'A natal/birth chart is a snapshot of the sky at the exact moment and location of your birth.',
        points: 1,
      },
      {
        id: 'f9',
        question: 'Which quality best describes Fixed signs?',
        type: 'multiple-choice',
        options: ['Adaptable and flexible', 'Determined and persistent', 'Initiating and pioneering', 'Emotional and intuitive'],
        correctIndices: [1],
        explanation: 'Fixed signs (Taurus, Leo, Scorpio, Aquarius) are known for their determination, persistence, and resistance to change.',
        points: 1,
      },
      {
        id: 'f10',
        question: 'Air signs are primarily associated with:',
        type: 'multiple-choice',
        options: ['Emotions and intuition', 'Communication and ideas', 'Physical action and passion', 'Material stability'],
        correctIndices: [1],
        explanation: 'Air signs (Gemini, Libra, Aquarius) are intellectual signs associated with communication, ideas, and social connection.',
        points: 1,
      },
    ],
  },

  // Module 2: Advanced Astrology (Aspects)
  'aspects': {
    id: 'test-aspects',
    title: 'Planetary Aspects Test',
    description: 'Test your understanding of how planets communicate through geometric relationships.',
    passingScore: 70,
    estimatedMinutes: 15,
    questions: [
      {
        id: 'a1',
        question: 'A conjunction occurs when two planets are approximately how many degrees apart?',
        type: 'multiple-choice',
        options: ['0°', '60°', '90°', '180°'],
        correctIndices: [0],
        explanation: 'A conjunction occurs when planets are at 0° (or very close), meaning they occupy the same area of the zodiac.',
        points: 1,
      },
      {
        id: 'a2',
        question: 'Which aspect is considered the most challenging and creates tension?',
        type: 'multiple-choice',
        options: ['Trine', 'Sextile', 'Square', 'Conjunction'],
        correctIndices: [2],
        explanation: 'The square (90°) creates friction and tension that demands action and growth.',
        points: 1,
      },
      {
        id: 'a3',
        question: 'A trine aspect is generally considered harmonious and flowing.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [0],
        explanation: 'Trines (120°) connect signs of the same element, creating natural harmony and easy energy flow.',
        points: 1,
      },
      {
        id: 'a4',
        question: 'Select all major aspects (Ptolemaic aspects):',
        type: 'multiple-select',
        options: ['Conjunction', 'Sextile', 'Quintile', 'Square', 'Trine', 'Opposition'],
        correctIndices: [0, 1, 3, 4, 5],
        explanation: 'The five major Ptolemaic aspects are conjunction (0°), sextile (60°), square (90°), trine (120°), and opposition (180°).',
        points: 2,
      },
      {
        id: 'a5',
        question: 'An opposition occurs at how many degrees?',
        type: 'multiple-choice',
        options: ['90°', '120°', '150°', '180°'],
        correctIndices: [3],
        explanation: 'An opposition occurs at 180°, placing planets directly across from each other in the chart.',
        points: 1,
      },
      {
        id: 'a6',
        question: 'A Grand Trine involves three planets all in what type of aspect to each other?',
        type: 'multiple-choice',
        options: ['Conjunction', 'Square', 'Trine', 'Opposition'],
        correctIndices: [2],
        explanation: 'A Grand Trine forms when three planets are each 120° apart, creating a triangular pattern of flowing energy.',
        points: 1,
      },
      {
        id: 'a7',
        question: 'The orb of an aspect refers to:',
        type: 'multiple-choice',
        options: [
          'The planet involved in the aspect',
          'The degree of allowance from exact',
          'The house where the aspect occurs',
          'The element of the signs involved',
        ],
        correctIndices: [1],
        explanation: 'The orb is the degree of deviation allowed from an exact aspect. Wider orbs mean weaker aspects.',
        points: 1,
      },
      {
        id: 'a8',
        question: 'A T-Square pattern involves which aspects?',
        type: 'multiple-select',
        options: ['Opposition', 'Trine', 'Two Squares', 'Sextile'],
        correctIndices: [0, 2],
        explanation: 'A T-Square consists of two planets in opposition, with a third planet squaring both, creating tension and drive.',
        points: 2,
      },
      {
        id: 'a9',
        question: 'An applying aspect is when the faster planet is moving toward exact aspect.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [0],
        explanation: 'Applying aspects (getting closer to exact) are considered stronger than separating aspects (moving apart).',
        points: 1,
      },
      {
        id: 'a10',
        question: 'The sextile (60°) is similar to a trine but requires more:',
        type: 'multiple-choice',
        options: ['Tension', 'Conscious effort', 'Conflict', 'Time'],
        correctIndices: [1],
        explanation: 'Sextiles offer opportunities and talents but require conscious effort to activate, unlike the automatic flow of trines.',
        points: 1,
      },
    ],
  },

  // Module for Mindset & Philosophy
  'mindset': {
    id: 'test-mindset',
    title: 'Mindset & Philosophy Test',
    description: 'Test your understanding of healthy approaches to astrology.',
    passingScore: 70,
    estimatedMinutes: 10,
    questions: [
      {
        id: 'm1',
        question: 'Astrology should be used as a tool for self-reflection rather than absolute prediction.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [0],
        explanation: 'Astrology is best used as a framework for self-understanding and growth, not deterministic fortune-telling.',
        points: 1,
      },
      {
        id: 'm2',
        question: 'Which approach to astrology is most empowering?',
        type: 'multiple-choice',
        options: [
          'Believing your fate is sealed by your chart',
          'Using it to understand tendencies and potentials',
          'Ignoring challenging placements',
          'Only focusing on predictions',
        ],
        correctIndices: [1],
        explanation: 'Understanding your chart as a map of potentials empowers you to work with your nature consciously.',
        points: 1,
      },
      {
        id: 'm3',
        question: 'A "difficult" planetary placement in a chart means the person will have a bad life.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [1],
        explanation: 'Challenging placements often indicate areas of growth and can lead to great strength when worked with consciously.',
        points: 1,
      },
      {
        id: 'm4',
        question: 'Select healthy ways to use astrology:',
        type: 'multiple-select',
        options: [
          'Self-reflection and understanding',
          'Making all decisions based on transits',
          'Understanding relationship dynamics',
          'Timing important activities',
          'Avoiding people with certain signs',
        ],
        correctIndices: [0, 2, 3],
        explanation: 'Astrology should enhance understanding and provide useful timing insights, not create fear or prejudice.',
        points: 2,
      },
      {
        id: 'm5',
        question: 'Free will and astrology are:',
        type: 'multiple-choice',
        options: [
          'Incompatible - astrology denies free will',
          'Compatible - astrology shows tendencies, not fate',
          'Unrelated concepts',
          'Only compatible in modern astrology',
        ],
        correctIndices: [1],
        explanation: 'Most modern astrologers view astrology as revealing tendencies and potentials that work alongside free will.',
        points: 1,
      },
    ],
  },

  // Module for History & Context
  'history': {
    id: 'test-history',
    title: 'History & Context Test',
    description: 'Test your knowledge of astrology\'s origins and evolution.',
    passingScore: 70,
    estimatedMinutes: 12,
    questions: [
      {
        id: 'h1',
        question: 'Astrology has been practiced for approximately how many years?',
        type: 'multiple-choice',
        options: ['500 years', '1,000 years', '3,000 years', '5,000+ years'],
        correctIndices: [3],
        explanation: 'Astrology dates back over 5,000 years to ancient Mesopotamia and has been practiced across many cultures.',
        points: 1,
      },
      {
        id: 'h2',
        question: 'Which ancient civilization is credited with developing the zodiac system we use today?',
        type: 'multiple-choice',
        options: ['Ancient Egypt', 'Ancient Greece', 'Mesopotamia/Babylon', 'Ancient China'],
        correctIndices: [2],
        explanation: 'The Babylonians developed the 12-sign zodiac system that was later refined by the Greeks.',
        points: 1,
      },
      {
        id: 'h3',
        question: 'Western astrology uses the tropical zodiac, which is based on:',
        type: 'multiple-choice',
        options: ['The fixed stars', 'The seasons/equinoxes', 'The Moon\'s position', 'The galactic center'],
        correctIndices: [1],
        explanation: 'The tropical zodiac begins at the spring equinox point, aligning with Earth\'s seasons rather than star positions.',
        points: 1,
      },
      {
        id: 'h4',
        question: 'Vedic/Indian astrology uses the sidereal zodiac.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [0],
        explanation: 'Vedic astrology uses the sidereal zodiac, which is aligned with the actual constellations in the sky.',
        points: 1,
      },
      {
        id: 'h5',
        question: 'Select all major astrological traditions:',
        type: 'multiple-select',
        options: ['Western/Tropical', 'Vedic/Jyotish', 'Chinese', 'Hellenistic', 'Digital'],
        correctIndices: [0, 1, 2, 3],
        explanation: 'Western, Vedic, Chinese, and Hellenistic are all major astrological traditions with distinct approaches.',
        points: 2,
      },
      {
        id: 'h6',
        question: 'The precession of the equinoxes causes the tropical and sidereal zodiacs to differ.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [0],
        explanation: 'Precession is the slow wobble of Earth\'s axis that causes the tropical zodiac to drift from the constellations over time.',
        points: 1,
      },
    ],
  },

  // Module for Personal Growth
  'growth': {
    id: 'test-growth',
    title: 'Personal Growth & Shadow Work Test',
    description: 'Test your understanding of using astrology for personal development.',
    passingScore: 70,
    estimatedMinutes: 10,
    questions: [
      {
        id: 'g1',
        question: 'In astrology, the "shadow" often relates to:',
        type: 'multiple-choice',
        options: [
          'Planets in the 12th house',
          'Repressed or underdeveloped parts of ourselves',
          'Retrograde planets only',
          'The Moon\'s nodes',
        ],
        correctIndices: [1],
        explanation: 'Shadow work involves recognizing and integrating parts of ourselves we\'ve repressed or denied.',
        points: 1,
      },
      {
        id: 'g2',
        question: 'Challenging aspects in a chart indicate areas of potential growth.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [0],
        explanation: 'Squares and oppositions often point to areas where we face challenges that catalyze personal growth.',
        points: 1,
      },
      {
        id: 'g3',
        question: 'Which placement is often associated with life purpose and soul growth?',
        type: 'multiple-choice',
        options: ['Mercury', 'The North Node', 'Venus', 'The Ascendant'],
        correctIndices: [1],
        explanation: 'The North Node indicates qualities and experiences we\'re meant to develop in this lifetime.',
        points: 1,
      },
      {
        id: 'g4',
        question: 'Select ways astrology can support personal growth:',
        type: 'multiple-select',
        options: [
          'Understanding emotional patterns (Moon)',
          'Recognizing relationship tendencies (Venus)',
          'Predicting exact future events',
          'Identifying communication style (Mercury)',
          'Working with challenging transits consciously',
        ],
        correctIndices: [0, 1, 3, 4],
        explanation: 'Astrology offers insights into our patterns and tendencies, supporting conscious self-development.',
        points: 2,
      },
      {
        id: 'g5',
        question: 'The South Node represents qualities we\'ve already mastered.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [0],
        explanation: 'The South Node shows innate talents and comfort zones from past experience, while North Node shows growth direction.',
        points: 1,
      },
    ],
  },

  // Module for Practical Daily Use
  'practical': {
    id: 'test-practical',
    title: 'Practical Daily Use Test',
    description: 'Test your knowledge of applying astrology to daily life.',
    passingScore: 70,
    estimatedMinutes: 12,
    questions: [
      {
        id: 'p1',
        question: 'The Moon changes signs approximately every:',
        type: 'multiple-choice',
        options: ['24 hours', '2.5 days', '1 week', '1 month'],
        correctIndices: [1],
        explanation: 'The Moon spends about 2.5 days in each sign, affecting daily emotional tones.',
        points: 1,
      },
      {
        id: 'p2',
        question: 'Mercury retrograde is a good time for:',
        type: 'multiple-select',
        options: [
          'Signing major contracts',
          'Reviewing past work',
          'Starting new projects',
          'Reconnecting with old friends',
          'Reflecting on communication',
        ],
        correctIndices: [1, 3, 4],
        explanation: 'Mercury retrograde favors review, revision, and reconnection rather than new beginnings.',
        points: 2,
      },
      {
        id: 'p3',
        question: 'The New Moon is traditionally associated with:',
        type: 'multiple-choice',
        options: ['Endings and release', 'New beginnings and intentions', 'Maximum energy', 'Conflict'],
        correctIndices: [1],
        explanation: 'New Moons mark the start of a new lunar cycle, ideal for setting intentions and new beginnings.',
        points: 1,
      },
      {
        id: 'p4',
        question: 'The Full Moon is a time of culmination and heightened emotions.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [0],
        explanation: 'Full Moons bring things to completion and often heighten emotions and illuminate what was hidden.',
        points: 1,
      },
      {
        id: 'p5',
        question: 'Void of Course Moon is traditionally a poor time for:',
        type: 'multiple-choice',
        options: ['Meditation', 'Starting important new ventures', 'Rest and routine', 'Creative daydreaming'],
        correctIndices: [1],
        explanation: 'Actions started during Void of Course Moon are said to "come to nothing" - better for routine tasks.',
        points: 1,
      },
      {
        id: 'p6',
        question: 'Which planet\'s retrograde has the most noticeable everyday effects?',
        type: 'multiple-choice',
        options: ['Neptune', 'Pluto', 'Mercury', 'Uranus'],
        correctIndices: [2],
        explanation: 'Mercury rules daily communication, travel, and technology, so its retrograde affects everyday life most noticeably.',
        points: 1,
      },
    ],
  },

  // Module for Reading for Others
  'reading-others': {
    id: 'test-reading-others',
    title: 'Ethics & Reading for Others Test',
    description: 'Test your understanding of ethical astrology practice.',
    passingScore: 70,
    estimatedMinutes: 10,
    questions: [
      {
        id: 'r1',
        question: 'When reading for others, you should always tell them exactly what will happen in their future.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [1],
        explanation: 'Ethical readings focus on potentials and possibilities, not deterministic predictions that remove agency.',
        points: 1,
      },
      {
        id: 'r2',
        question: 'Select ethical practices when reading for others:',
        type: 'multiple-select',
        options: [
          'Using empowering language',
          'Predicting death or illness',
          'Respecting client confidentiality',
          'Offering constructive guidance',
          'Making clients dependent on readings',
        ],
        correctIndices: [0, 2, 3],
        explanation: 'Ethical practice involves empowerment, confidentiality, and constructive guidance without creating dependency.',
        points: 2,
      },
      {
        id: 'r3',
        question: 'It\'s appropriate to read someone\'s chart without their permission.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [1],
        explanation: 'Reading charts without consent raises ethical concerns about privacy and respect for others.',
        points: 1,
      },
      {
        id: 'r4',
        question: 'When encountering challenging placements in a client\'s chart, you should:',
        type: 'multiple-choice',
        options: [
          'Avoid mentioning them entirely',
          'Scare them with worst-case scenarios',
          'Present them as areas for growth and awareness',
          'Tell them their life will be difficult',
        ],
        correctIndices: [2],
        explanation: 'Challenging placements should be framed constructively as opportunities for growth and self-awareness.',
        points: 1,
      },
      {
        id: 'r5',
        question: 'A good astrologer empowers clients to make their own decisions.',
        type: 'true-false',
        options: ['True', 'False'],
        correctIndices: [0],
        explanation: 'The goal of ethical astrology is to provide insight that empowers clients, not to make decisions for them.',
        points: 1,
      },
    ],
  },
}

// Helper function to get a module test
export function getModuleTest(moduleId: string): ModuleTest | undefined {
  return MODULE_TESTS[moduleId]
}

// Get all module IDs that have tests
export function getModulesWithTests(): string[] {
  return Object.keys(MODULE_TESTS)
}
