/**
 * Report Definitions
 *
 * Defines the available reports users can purchase
 */

import type { ReportDefinition, ReportSlug } from '@/types'

export const reports: Record<ReportSlug, ReportDefinition> = {
  'personality-deep-dive': {
    slug: 'personality-deep-dive',
    title: 'Personality Deep Dive',
    subtitle: 'Understand yourself at your core',
    description:
      'A comprehensive exploration of your unique personality based on your complete birth chart. Discover your core motivations, emotional patterns, communication style, relationship needs, and life purpose.',
    price: 29,
    wordCount: '2,500-3,500 words',
    deliveryTime: 'Instant',
    icon: '🪞',
    gradient: 'from-violet-500 to-purple-600',
    features: [
      'Complete Sun, Moon & Rising analysis',
      'Your emotional landscape & inner needs',
      'Communication style & mental patterns',
      'Love language & relationship approach',
      'Career strengths & working style',
      'Life purpose & soul mission',
      'Shadow work & growth areas',
      'Personalized affirmations',
    ],
    sampleSections: [
      'The Essence of You (Sun Sign Deep Dive)',
      'Your Inner World (Moon Sign Analysis)',
      'How Others See You (Rising Sign)',
      'Mind & Communication (Mercury)',
      'Love & Values (Venus)',
      'Drive & Ambition (Mars)',
      'Growth & Opportunity (Jupiter)',
      'Challenges & Mastery (Saturn)',
      'Your Life Purpose (North Node)',
      'Healing Journey (Chiron)',
    ],
  },
  'relationship-compatibility': {
    slug: 'relationship-compatibility',
    title: 'Relationship Compatibility',
    subtitle: 'Understand your cosmic connection',
    description:
      'An in-depth synastry analysis exploring the dynamics between you and your partner. Discover your strengths as a couple, potential challenges, and how to nurture your connection.',
    price: 29,
    wordCount: '2,500-3,500 words',
    deliveryTime: 'Instant',
    icon: '💞',
    gradient: 'from-rose-500 to-pink-600',
    requiresPartner: true,
    features: [
      'Complete synastry chart comparison',
      'Emotional compatibility analysis',
      'Communication dynamics',
      'Physical & romantic chemistry',
      'Long-term relationship potential',
      'Areas of natural harmony',
      'Growth opportunities together',
      'Practical relationship advice',
    ],
    sampleSections: [
      'Your Connection at a Glance',
      'Emotional Bond (Moon Connections)',
      'Communication Styles (Mercury Aspects)',
      'Romantic Chemistry (Venus Interactions)',
      'Physical Attraction (Mars Dynamics)',
      'Growth Together (Jupiter Aspects)',
      'Commitment & Stability (Saturn)',
      'Karmic Connections',
      'Challenges & How to Navigate Them',
      'Your Relationship Superpower',
    ],
  },
  'year-ahead-forecast': {
    slug: 'year-ahead-forecast',
    title: 'Year Ahead Forecast',
    subtitle: 'Navigate your next 12 months',
    description:
      'A comprehensive forecast covering the major astrological influences affecting you over the next year. Get month-by-month insights, key dates, and practical guidance.',
    price: 29,
    wordCount: '2,500-3,500 words',
    deliveryTime: 'Instant',
    icon: '🔮',
    gradient: 'from-indigo-500 to-blue-600',
    features: [
      'Month-by-month breakdown',
      'Major transit influences',
      'Career & financial outlook',
      'Relationship forecasts',
      'Health & wellness windows',
      'Key dates to watch',
      'Best times for major decisions',
      'Personal growth opportunities',
    ],
    sampleSections: [
      'Your Year at a Glance',
      'Major Themes for the Year',
      'Career & Professional Life',
      'Love & Relationships',
      'Health & Wellness',
      'Personal Growth & Spirituality',
      'Month-by-Month Breakdown',
      'Key Dates & Power Days',
      'Eclipses & Their Impact',
      'Closing Thoughts & Guidance',
    ],
  },
  'monthly-forecast': {
    slug: 'monthly-forecast',
    title: 'Monthly Forecast',
    subtitle: 'Your personalized month ahead',
    description:
      'A detailed guide to your upcoming month with week-by-week breakdowns, daily energy patterns, optimal timing for activities, and personalized guidance based on your birth chart.',
    price: 0,
    wordCount: '2,500-3,500 words',
    deliveryTime: 'Instant',
    icon: '📅',
    gradient: 'from-amber-500 to-orange-600',
    features: [
      'Week-by-week detailed breakdown',
      'Daily energy & mood patterns',
      'Best days for career moves',
      'Optimal romance & relationship days',
      'Financial decision timing',
      'Health & self-care windows',
      'Mercury retrograde guidance',
      'Moon phase activities',
      'Personal transit interpretations',
      'Interactive daily energy chart',
    ],
    sampleSections: [
      'Your Month at a Glance',
      'This Month\'s Cosmic Weather',
      'Week 1: New Beginnings',
      'Week 2: Building Momentum',
      'Week 3: Peak Energy',
      'Week 4: Reflection & Preparation',
      'Love & Relationships This Month',
      'Career & Finances This Month',
      'Health & Wellness Guide',
      'Best Days Calendar',
      'Moon Phase Rituals',
      'Personal Growth Focus',
    ],
  },
  'past-life-karma': {
    slug: 'past-life-karma',
    title: 'Past Life & Karma Report',
    subtitle: 'Explore your soul\'s journey',
    description:
      'A profound exploration of your karmic patterns, past life themes, and soul purpose. Discover what your chart reveals about lessons carried from previous incarnations and your evolutionary path in this lifetime.',
    price: 29,
    wordCount: '2,500-3,500 words',
    deliveryTime: 'Instant',
    icon: '🌙',
    gradient: 'from-purple-600 to-indigo-700',
    features: [
      'South Node past life analysis',
      'North Node soul purpose',
      'Karmic debt indicators',
      'Past life talents & gifts',
      '12th house mysteries revealed',
      'Saturn\'s karmic lessons',
      'Retrograde planet meanings',
      'Healing ancestral patterns',
      'Soul contract insights',
      'Evolutionary growth path',
    ],
    sampleSections: [
      'Your Soul\'s Journey Overview',
      'The South Node: Where You\'ve Been',
      'The North Node: Where You\'re Going',
      'Saturn\'s Karmic Lessons',
      'The 12th House: Hidden Karma',
      'Retrograde Planets: Unfinished Business',
      'Karmic Relationship Patterns',
      'Past Life Talents to Reclaim',
      'Ancestral Healing',
      'Your Evolutionary Path Forward',
    ],
  },
  'financial-potential': {
    slug: 'financial-potential',
    title: 'Financial Potential Report',
    subtitle: 'Unlock your wealth blueprint',
    description:
      'A comprehensive analysis of your financial potential based on your birth chart. Discover your natural money-making abilities, investment style, career prosperity indicators, and optimal timing for financial decisions.',
    price: 29,
    wordCount: '2,500-3,500 words',
    deliveryTime: 'Instant',
    icon: '💎',
    gradient: 'from-emerald-500 to-teal-600',
    features: [
      '2nd house wealth analysis',
      '8th house shared resources',
      'Career & earning potential',
      'Natural money-making talents',
      'Investment style profile',
      'Financial risk tolerance',
      'Best timing for money moves',
      'Abundance blocks to clear',
      'Prosperity transits ahead',
      'Wealth manifestation guidance',
    ],
    sampleSections: [
      'Your Financial Blueprint Overview',
      'The 2nd House: Personal Resources',
      'The 8th House: Shared Wealth & Investments',
      'The 10th House: Career & Income Potential',
      'Venus & Jupiter: Abundance Indicators',
      'Saturn & Pluto: Financial Discipline',
      'Your Money Mindset Profile',
      'Investment & Risk Style',
      'Timing Your Financial Moves',
      'Clearing Abundance Blocks',
      'Your Wealth Manifestation Path',
    ],
  },
  'partner-compatibility': {
    slug: 'partner-compatibility',
    title: 'Deep Compatibility Analysis',
    subtitle: 'The complete picture of your partnership',
    description:
      'An extensive synastry and composite chart analysis exploring every dimension of your relationship. From emotional bonds to long-term potential, discover the cosmic blueprint of your partnership.',
    price: 29,
    wordCount: '2,000-3,000 words',
    deliveryTime: 'Instant',
    icon: '💑',
    gradient: 'from-pink-500 to-rose-600',
    requiresPartner: true,
    features: [
      'Complete synastry analysis',
      'Composite chart interpretation',
      'Emotional compatibility depth',
      'Communication dynamics',
      'Physical & romantic chemistry',
      'Trust & commitment factors',
      'Conflict resolution styles',
      'Long-term growth potential',
      'Karmic connections revealed',
      'Relationship timing insights',
    ],
    sampleSections: [
      'Your Partnership Overview',
      'The Composite Chart: Your Relationship Entity',
      'Sun & Moon Connections: Core Compatibility',
      'Venus & Mars: Love & Desire',
      'Mercury Aspects: Communication',
      'Saturn Bonds: Commitment & Structure',
      'Outer Planet Connections: Transformation',
      'Karmic Ties: Past Life Links',
      'Growth Opportunities Together',
      'Navigating Challenges',
      'Your Relationship\'s Higher Purpose',
    ],
  },
}

export const reportsList = Object.values(reports)

export function getReportBySlug(slug: string): ReportDefinition | undefined {
  return reports[slug as ReportSlug]
}
