/**
 * Tarot Card Definitions
 *
 * Complete Rider-Waite deck with 78 cards.
 * Card IDs match image filenames in /public/tarot/cards/
 */

import type { TarotCard } from '@/types/tarot'

export const MAJOR_ARCANA: TarotCard[] = [
  {
    id: 'the-fool',
    name: 'The Fool',
    suit: 'major',
    number: 0,
    keywords: ['beginnings', 'innocence', 'spontaneity', 'free spirit'],
    uprightMeaning: 'New beginnings, innocence, spontaneity, a free spirit. Taking a leap of faith.',
    reversedMeaning: 'Holding back, recklessness, risk-taking, foolishness.',
    image: '/tarot/cards/the-fool.jpg',
  },
  {
    id: 'the-magician',
    name: 'The Magician',
    suit: 'major',
    number: 1,
    keywords: ['manifestation', 'resourcefulness', 'power', 'inspired action'],
    uprightMeaning: 'Manifestation, resourcefulness, power, inspired action. You have all the tools you need.',
    reversedMeaning: 'Manipulation, poor planning, untapped talents, wasted potential.',
    image: '/tarot/cards/the-magician.jpg',
  },
  {
    id: 'the-high-priestess',
    name: 'The High Priestess',
    suit: 'major',
    number: 2,
    keywords: ['intuition', 'mystery', 'subconscious', 'inner knowledge'],
    uprightMeaning: 'Intuition, sacred knowledge, divine feminine, the subconscious mind.',
    reversedMeaning: 'Secrets, disconnected from intuition, withdrawal, silence.',
    image: '/tarot/cards/the-high-priestess.jpg',
  },
  {
    id: 'the-empress',
    name: 'The Empress',
    suit: 'major',
    number: 3,
    keywords: ['femininity', 'beauty', 'nature', 'nurturing', 'abundance'],
    uprightMeaning: 'Femininity, beauty, nature, nurturing, abundance. Creative expression and fertility.',
    reversedMeaning: 'Creative block, dependence on others, neglecting self-care.',
    image: '/tarot/cards/the-empress.jpg',
  },
  {
    id: 'the-emperor',
    name: 'The Emperor',
    suit: 'major',
    number: 4,
    keywords: ['authority', 'structure', 'control', 'father figure'],
    uprightMeaning: 'Authority, establishment, structure, a father figure. Leadership and stability.',
    reversedMeaning: 'Domination, excessive control, lack of discipline, inflexibility.',
    image: '/tarot/cards/the-emperor.jpg',
  },
  {
    id: 'the-hierophant',
    name: 'The Hierophant',
    suit: 'major',
    number: 5,
    keywords: ['spiritual wisdom', 'tradition', 'conformity', 'morality'],
    uprightMeaning: 'Spiritual wisdom, religious beliefs, conformity, tradition, institutions.',
    reversedMeaning: 'Personal beliefs, freedom, challenging the status quo, unconventionality.',
    image: '/tarot/cards/the-hierophant.jpg',
  },
  {
    id: 'the-lovers',
    name: 'The Lovers',
    suit: 'major',
    number: 6,
    keywords: ['love', 'harmony', 'relationships', 'choices', 'alignment'],
    uprightMeaning: 'Love, harmony, relationships, values alignment, choices in love.',
    reversedMeaning: 'Self-love, disharmony, imbalance, misalignment of values.',
    image: '/tarot/cards/the-lovers.jpg',
  },
  {
    id: 'the-chariot',
    name: 'The Chariot',
    suit: 'major',
    number: 7,
    keywords: ['control', 'willpower', 'success', 'action', 'determination'],
    uprightMeaning: 'Control, willpower, success, action, determination. Victory through focus.',
    reversedMeaning: 'Self-discipline lacking, opposition, lack of direction.',
    image: '/tarot/cards/the-chariot.jpg',
  },
  {
    id: 'strength',
    name: 'Strength',
    suit: 'major',
    number: 8,
    keywords: ['courage', 'persuasion', 'influence', 'compassion'],
    uprightMeaning: 'Strength, courage, persuasion, influence, compassion. Inner power.',
    reversedMeaning: 'Inner strength, self-doubt, low energy, raw emotion.',
    image: '/tarot/cards/strength.jpg',
  },
  {
    id: 'the-hermit',
    name: 'The Hermit',
    suit: 'major',
    number: 9,
    keywords: ['soul-searching', 'introspection', 'solitude', 'inner guidance'],
    uprightMeaning: 'Soul-searching, introspection, being alone, inner guidance. Seeking truth.',
    reversedMeaning: 'Isolation, loneliness, withdrawal, lost your way.',
    image: '/tarot/cards/the-hermit.jpg',
  },
  {
    id: 'wheel-of-fortune',
    name: 'Wheel of Fortune',
    suit: 'major',
    number: 10,
    keywords: ['change', 'cycles', 'fate', 'destiny', 'turning point'],
    uprightMeaning: 'Good luck, karma, life cycles, destiny, a turning point.',
    reversedMeaning: 'Bad luck, resistance to change, breaking cycles.',
    image: '/tarot/cards/wheel-of-fortune.jpg',
  },
  {
    id: 'justice',
    name: 'Justice',
    suit: 'major',
    number: 11,
    keywords: ['justice', 'fairness', 'truth', 'law', 'cause and effect'],
    uprightMeaning: 'Justice, fairness, truth, cause and effect, law. Accountability.',
    reversedMeaning: 'Unfairness, lack of accountability, dishonesty.',
    image: '/tarot/cards/justice.jpg',
  },
  {
    id: 'the-hanged-man',
    name: 'The Hanged Man',
    suit: 'major',
    number: 12,
    keywords: ['pause', 'surrender', 'letting go', 'new perspective'],
    uprightMeaning: 'Pause, surrender, letting go, new perspectives. Seeing things differently.',
    reversedMeaning: 'Delays, resistance, stalling, indecision.',
    image: '/tarot/cards/the-hanged-man.jpg',
  },
  {
    id: 'death',
    name: 'Death',
    suit: 'major',
    number: 13,
    keywords: ['endings', 'change', 'transformation', 'transition'],
    uprightMeaning: 'Endings, change, transformation, transition. Closing one chapter to begin another.',
    reversedMeaning: 'Resistance to change, personal transformation, inner purging.',
    image: '/tarot/cards/death.jpg',
  },
  {
    id: 'temperance',
    name: 'Temperance',
    suit: 'major',
    number: 14,
    keywords: ['balance', 'moderation', 'patience', 'purpose'],
    uprightMeaning: 'Balance, moderation, patience, purpose. Finding middle ground.',
    reversedMeaning: 'Imbalance, excess, self-healing, re-alignment.',
    image: '/tarot/cards/temperance.jpg',
  },
  {
    id: 'the-devil',
    name: 'The Devil',
    suit: 'major',
    number: 15,
    keywords: ['shadow self', 'attachment', 'addiction', 'restriction'],
    uprightMeaning: 'Shadow self, attachment, addiction, restriction, sexuality.',
    reversedMeaning: 'Releasing limiting beliefs, exploring dark thoughts, detachment.',
    image: '/tarot/cards/the-devil.jpg',
  },
  {
    id: 'the-tower',
    name: 'The Tower',
    suit: 'major',
    number: 16,
    keywords: ['sudden change', 'upheaval', 'chaos', 'revelation', 'awakening'],
    uprightMeaning: 'Sudden change, upheaval, chaos, revelation, awakening. Breaking down false structures.',
    reversedMeaning: 'Personal transformation, fear of change, averting disaster.',
    image: '/tarot/cards/the-tower.jpg',
  },
  {
    id: 'the-star',
    name: 'The Star',
    suit: 'major',
    number: 17,
    keywords: ['hope', 'faith', 'purpose', 'renewal', 'spirituality'],
    uprightMeaning: 'Hope, faith, purpose, renewal, spirituality. Healing and inspiration.',
    reversedMeaning: 'Lack of faith, despair, self-trust, disconnection.',
    image: '/tarot/cards/the-star.jpg',
  },
  {
    id: 'the-moon',
    name: 'The Moon',
    suit: 'major',
    number: 18,
    keywords: ['illusion', 'fear', 'anxiety', 'subconscious', 'intuition'],
    uprightMeaning: 'Illusion, fear, anxiety, subconscious, intuition. Things are not as they seem.',
    reversedMeaning: 'Release of fear, repressed emotion, inner confusion.',
    image: '/tarot/cards/the-moon.jpg',
  },
  {
    id: 'the-sun',
    name: 'The Sun',
    suit: 'major',
    number: 19,
    keywords: ['positivity', 'fun', 'warmth', 'success', 'vitality'],
    uprightMeaning: 'Positivity, fun, warmth, success, vitality. Joy and celebration.',
    reversedMeaning: 'Inner child, feeling down, overly optimistic.',
    image: '/tarot/cards/the-sun.jpg',
  },
  {
    id: 'judgement',
    name: 'Judgement',
    suit: 'major',
    number: 20,
    keywords: ['judgement', 'rebirth', 'inner calling', 'absolution'],
    uprightMeaning: 'Judgement, rebirth, inner calling, absolution. A spiritual awakening.',
    reversedMeaning: 'Self-doubt, inner critic, ignoring the call.',
    image: '/tarot/cards/judgement.jpg',
  },
  {
    id: 'the-world',
    name: 'The World',
    suit: 'major',
    number: 21,
    keywords: ['completion', 'integration', 'accomplishment', 'travel'],
    uprightMeaning: 'Completion, integration, accomplishment, travel. A successful conclusion.',
    reversedMeaning: 'Seeking personal closure, short-cuts, delays.',
    image: '/tarot/cards/the-world.jpg',
  },
]

export const WANDS: TarotCard[] = [
  {
    id: 'ace-of-wands',
    name: 'Ace of Wands',
    suit: 'wands',
    number: 1,
    keywords: ['inspiration', 'new opportunities', 'growth', 'potential'],
    uprightMeaning: 'Inspiration, new opportunities, growth, potential. A spark of creativity.',
    reversedMeaning: 'An emerging idea, lack of direction, distractions, delays.',
    image: '/tarot/cards/ace-of-wands.jpg',
  },
  {
    id: 'two-of-wands',
    name: 'Two of Wands',
    suit: 'wands',
    number: 2,
    keywords: ['future planning', 'progress', 'decisions', 'discovery'],
    uprightMeaning: 'Future planning, progress, decisions, discovery. Weighing options.',
    reversedMeaning: 'Personal goals, inner alignment, fear of unknown, lack of planning.',
    image: '/tarot/cards/two-of-wands.jpg',
  },
  {
    id: 'three-of-wands',
    name: 'Three of Wands',
    suit: 'wands',
    number: 3,
    keywords: ['progress', 'expansion', 'foresight', 'overseas opportunities'],
    uprightMeaning: 'Progress, expansion, foresight, overseas opportunities. Looking ahead.',
    reversedMeaning: 'Playing small, lack of foresight, unexpected delays.',
    image: '/tarot/cards/three-of-wands.jpg',
  },
  {
    id: 'four-of-wands',
    name: 'Four of Wands',
    suit: 'wands',
    number: 4,
    keywords: ['celebration', 'joy', 'harmony', 'relaxation', 'homecoming'],
    uprightMeaning: 'Celebration, joy, harmony, relaxation, homecoming. A milestone.',
    reversedMeaning: 'Personal celebration, inner harmony, conflict with others.',
    image: '/tarot/cards/four-of-wands.jpg',
  },
  {
    id: 'five-of-wands',
    name: 'Five of Wands',
    suit: 'wands',
    number: 5,
    keywords: ['conflict', 'disagreements', 'competition', 'tension'],
    uprightMeaning: 'Conflict, disagreements, competition, tension, diversity of opinion.',
    reversedMeaning: 'Inner conflict, conflict avoidance, tension release.',
    image: '/tarot/cards/five-of-wands.jpg',
  },
  {
    id: 'six-of-wands',
    name: 'Six of Wands',
    suit: 'wands',
    number: 6,
    keywords: ['success', 'public recognition', 'progress', 'self-confidence'],
    uprightMeaning: 'Success, public recognition, progress, self-confidence. Victory.',
    reversedMeaning: 'Private achievement, personal definition of success, fall from grace.',
    image: '/tarot/cards/six-of-wands.jpg',
  },
  {
    id: 'seven-of-wands',
    name: 'Seven of Wands',
    suit: 'wands',
    number: 7,
    keywords: ['challenge', 'competition', 'protection', 'perseverance'],
    uprightMeaning: 'Challenge, competition, protection, perseverance. Standing your ground.',
    reversedMeaning: 'Exhaustion, giving up, overwhelmed.',
    image: '/tarot/cards/seven-of-wands.jpg',
  },
  {
    id: 'eight-of-wands',
    name: 'Eight of Wands',
    suit: 'wands',
    number: 8,
    keywords: ['movement', 'fast paced change', 'action', 'alignment'],
    uprightMeaning: 'Movement, fast paced change, action, alignment, air travel.',
    reversedMeaning: 'Delays, frustration, resisting change, internal alignment.',
    image: '/tarot/cards/eight-of-wands.jpg',
  },
  {
    id: 'nine-of-wands',
    name: 'Nine of Wands',
    suit: 'wands',
    number: 9,
    keywords: ['resilience', 'courage', 'persistence', 'test of faith'],
    uprightMeaning: 'Resilience, courage, persistence, test of faith, boundaries.',
    reversedMeaning: 'Inner resources, struggle, overwhelm, defensive.',
    image: '/tarot/cards/nine-of-wands.jpg',
  },
  {
    id: 'ten-of-wands',
    name: 'Ten of Wands',
    suit: 'wands',
    number: 10,
    keywords: ['burden', 'extra responsibility', 'hard work', 'completion'],
    uprightMeaning: 'Burden, extra responsibility, hard work, completion. Carrying too much.',
    reversedMeaning: 'Doing it all, delegation, release of burden.',
    image: '/tarot/cards/ten-of-wands.jpg',
  },
  {
    id: 'page-of-wands',
    name: 'Page of Wands',
    suit: 'wands',
    number: 11,
    keywords: ['inspiration', 'ideas', 'discovery', 'limitless potential'],
    uprightMeaning: 'Inspiration, ideas, discovery, limitless potential, free spirit.',
    reversedMeaning: 'Newly formed ideas, lack of direction, procrastination.',
    image: '/tarot/cards/page-of-wands.jpg',
  },
  {
    id: 'knight-of-wands',
    name: 'Knight of Wands',
    suit: 'wands',
    number: 12,
    keywords: ['energy', 'passion', 'inspired action', 'adventure'],
    uprightMeaning: 'Energy, passion, inspired action, adventure, impulsiveness.',
    reversedMeaning: 'Passion project, haste, scattered energy, delays in travel.',
    image: '/tarot/cards/knight-of-wands.jpg',
  },
  {
    id: 'queen-of-wands',
    name: 'Queen of Wands',
    suit: 'wands',
    number: 13,
    keywords: ['courage', 'confidence', 'independence', 'determination'],
    uprightMeaning: 'Courage, confidence, independence, social butterfly, determination.',
    reversedMeaning: 'Self-respect, self-confidence, introverted, re-establish sense of self.',
    image: '/tarot/cards/queen-of-wands.jpg',
  },
  {
    id: 'king-of-wands',
    name: 'King of Wands',
    suit: 'wands',
    number: 14,
    keywords: ['natural-born leader', 'vision', 'entrepreneur', 'honour'],
    uprightMeaning: 'Natural-born leader, vision, entrepreneur, honour. Taking charge.',
    reversedMeaning: 'Impulsiveness, haste, ruthless, high expectations.',
    image: '/tarot/cards/king-of-wands.jpg',
  },
]

export const CUPS: TarotCard[] = [
  {
    id: 'ace-of-cups',
    name: 'Ace of Cups',
    suit: 'cups',
    number: 1,
    keywords: ['love', 'new relationships', 'compassion', 'creativity'],
    uprightMeaning: 'Love, new relationships, compassion, creativity. Emotional new beginning.',
    reversedMeaning: 'Self-love, intuition, repressed emotions.',
    image: '/tarot/cards/ace-of-cups.jpg',
  },
  {
    id: 'two-of-cups',
    name: 'Two of Cups',
    suit: 'cups',
    number: 2,
    keywords: ['unified love', 'partnership', 'mutual attraction'],
    uprightMeaning: 'Unified love, partnership, mutual attraction. A deep connection.',
    reversedMeaning: 'Self-love, break-up, disharmony, distrust.',
    image: '/tarot/cards/two-of-cups.jpg',
  },
  {
    id: 'three-of-cups',
    name: 'Three of Cups',
    suit: 'cups',
    number: 3,
    keywords: ['celebration', 'friendship', 'creativity', 'collaborations'],
    uprightMeaning: 'Celebration, friendship, creativity, collaborations. Joy with others.',
    reversedMeaning: 'Independence, alone time, hardcore partying, "third party" in a relationship.',
    image: '/tarot/cards/three-of-cups.jpg',
  },
  {
    id: 'four-of-cups',
    name: 'Four of Cups',
    suit: 'cups',
    number: 4,
    keywords: ['meditation', 'contemplation', 'apathy', 're-evaluation'],
    uprightMeaning: 'Meditation, contemplation, apathy, re-evaluation. Missing opportunities.',
    reversedMeaning: 'Retreat, withdrawal, checking in for alignment.',
    image: '/tarot/cards/four-of-cups.jpg',
  },
  {
    id: 'five-of-cups',
    name: 'Five of Cups',
    suit: 'cups',
    number: 5,
    keywords: ['regret', 'failure', 'disappointment', 'pessimism'],
    uprightMeaning: 'Regret, failure, disappointment, pessimism. Focusing on loss.',
    reversedMeaning: 'Personal setbacks, self-forgiveness, moving on.',
    image: '/tarot/cards/five-of-cups.jpg',
  },
  {
    id: 'six-of-cups',
    name: 'Six of Cups',
    suit: 'cups',
    number: 6,
    keywords: ['revisiting the past', 'childhood memories', 'innocence', 'joy'],
    uprightMeaning: 'Revisiting the past, childhood memories, innocence, joy. Nostalgia.',
    reversedMeaning: 'Living in the past, forgiveness, lacking playfulness.',
    image: '/tarot/cards/six-of-cups.jpg',
  },
  {
    id: 'seven-of-cups',
    name: 'Seven of Cups',
    suit: 'cups',
    number: 7,
    keywords: ['opportunities', 'choices', 'wishful thinking', 'illusion'],
    uprightMeaning: 'Opportunities, choices, wishful thinking, illusion. Too many options.',
    reversedMeaning: 'Alignment, personal values, overwhelmed by choices.',
    image: '/tarot/cards/seven-of-cups.jpg',
  },
  {
    id: 'eight-of-cups',
    name: 'Eight of Cups',
    suit: 'cups',
    number: 8,
    keywords: ['disappointment', 'abandonment', 'withdrawal', 'escapism'],
    uprightMeaning: 'Disappointment, abandonment, withdrawal, escapism. Walking away.',
    reversedMeaning: 'Trying one more time, indecision, aimless drifting.',
    image: '/tarot/cards/eight-of-cups.jpg',
  },
  {
    id: 'nine-of-cups',
    name: 'Nine of Cups',
    suit: 'cups',
    number: 9,
    keywords: ['contentment', 'satisfaction', 'gratitude', 'wish come true'],
    uprightMeaning: 'Contentment, satisfaction, gratitude, wish come true. Emotional fulfillment.',
    reversedMeaning: 'Inner happiness, materialism, dissatisfaction.',
    image: '/tarot/cards/nine-of-cups.jpg',
  },
  {
    id: 'ten-of-cups',
    name: 'Ten of Cups',
    suit: 'cups',
    number: 10,
    keywords: ['divine love', 'blissful relationships', 'harmony', 'alignment'],
    uprightMeaning: 'Divine love, blissful relationships, harmony, alignment. Emotional fulfillment.',
    reversedMeaning: 'Disconnection, misaligned values, struggling relationships.',
    image: '/tarot/cards/ten-of-cups.jpg',
  },
  {
    id: 'page-of-cups',
    name: 'Page of Cups',
    suit: 'cups',
    number: 11,
    keywords: ['creative opportunities', 'intuitive messages', 'curiosity'],
    uprightMeaning: 'Creative opportunities, intuitive messages, curiosity, possibility.',
    reversedMeaning: 'New ideas, doubting intuition, creative blocks, emotional immaturity.',
    image: '/tarot/cards/page-of-cups.jpg',
  },
  {
    id: 'knight-of-cups',
    name: 'Knight of Cups',
    suit: 'cups',
    number: 12,
    keywords: ['creativity', 'romance', 'charm', 'imagination'],
    uprightMeaning: 'Creativity, romance, charm, imagination, beauty. Following your heart.',
    reversedMeaning: 'Overactive imagination, unrealistic, jealousy, moodiness.',
    image: '/tarot/cards/knight-of-cups.jpg',
  },
  {
    id: 'queen-of-cups',
    name: 'Queen of Cups',
    suit: 'cups',
    number: 13,
    keywords: ['compassion', 'calm', 'comfort', 'intuition'],
    uprightMeaning: 'Compassionate, caring, emotionally stable, intuitive, in flow.',
    reversedMeaning: 'Inner feelings, self-care, self-love, co-dependency.',
    image: '/tarot/cards/queen-of-cups.jpg',
  },
  {
    id: 'king-of-cups',
    name: 'King of Cups',
    suit: 'cups',
    number: 14,
    keywords: ['emotionally balanced', 'compassionate', 'diplomatic'],
    uprightMeaning: 'Emotionally balanced, compassionate, diplomatic. Mastery of emotions.',
    reversedMeaning: 'Self-compassion, inner feelings, moodiness, emotionally manipulative.',
    image: '/tarot/cards/king-of-cups.jpg',
  },
]

export const SWORDS: TarotCard[] = [
  {
    id: 'ace-of-swords',
    name: 'Ace of Swords',
    suit: 'swords',
    number: 1,
    keywords: ['breakthroughs', 'new ideas', 'mental clarity', 'success'],
    uprightMeaning: 'Breakthroughs, new ideas, mental clarity, success. A moment of truth.',
    reversedMeaning: 'Inner clarity, re-thinking an idea, clouded judgement.',
    image: '/tarot/cards/ace-of-swords.jpg',
  },
  {
    id: 'two-of-swords',
    name: 'Two of Swords',
    suit: 'swords',
    number: 2,
    keywords: ['difficult decisions', 'weighing options', 'impasse', 'avoidance'],
    uprightMeaning: 'Difficult decisions, weighing up options, an impasse, avoidance.',
    reversedMeaning: 'Indecision, confusion, information overload, stalemate.',
    image: '/tarot/cards/two-of-swords.jpg',
  },
  {
    id: 'three-of-swords',
    name: 'Three of Swords',
    suit: 'swords',
    number: 3,
    keywords: ['heartbreak', 'emotional pain', 'sorrow', 'grief'],
    uprightMeaning: 'Heartbreak, emotional pain, sorrow, grief, hurt. Processing pain.',
    reversedMeaning: 'Negative self-talk, releasing pain, optimism, forgiveness.',
    image: '/tarot/cards/three-of-swords.jpg',
  },
  {
    id: 'four-of-swords',
    name: 'Four of Swords',
    suit: 'swords',
    number: 4,
    keywords: ['rest', 'relaxation', 'meditation', 'contemplation', 'recuperation'],
    uprightMeaning: 'Rest, relaxation, meditation, contemplation, recuperation.',
    reversedMeaning: 'Exhaustion, burn-out, deep contemplation, stagnation.',
    image: '/tarot/cards/four-of-swords.jpg',
  },
  {
    id: 'five-of-swords',
    name: 'Five of Swords',
    suit: 'swords',
    number: 5,
    keywords: ['conflict', 'disagreements', 'competition', 'defeat'],
    uprightMeaning: 'Conflict, disagreements, competition, defeat, winning at all costs.',
    reversedMeaning: 'Reconciliation, making amends, past resentment.',
    image: '/tarot/cards/five-of-swords.jpg',
  },
  {
    id: 'six-of-swords',
    name: 'Six of Swords',
    suit: 'swords',
    number: 6,
    keywords: ['transition', 'change', 'rite of passage', 'releasing baggage'],
    uprightMeaning: 'Transition, change, rite of passage, releasing baggage. Moving on.',
    reversedMeaning: 'Personal transition, resistance to change, unfinished business.',
    image: '/tarot/cards/six-of-swords.jpg',
  },
  {
    id: 'seven-of-swords',
    name: 'Seven of Swords',
    suit: 'swords',
    number: 7,
    keywords: ['betrayal', 'deception', 'getting away with something', 'strategy'],
    uprightMeaning: 'Betrayal, deception, getting away with something, acting strategically.',
    reversedMeaning: 'Imposter syndrome, self-deceit, keeping secrets.',
    image: '/tarot/cards/seven-of-swords.jpg',
  },
  {
    id: 'eight-of-swords',
    name: 'Eight of Swords',
    suit: 'swords',
    number: 8,
    keywords: ['negative thoughts', 'self-imposed restriction', 'imprisonment'],
    uprightMeaning: 'Negative thoughts, self-imposed restriction, imprisonment, victim mentality.',
    reversedMeaning: 'Self-limiting beliefs, inner critic, releasing negative thoughts.',
    image: '/tarot/cards/eight-of-swords.jpg',
  },
  {
    id: 'nine-of-swords',
    name: 'Nine of Swords',
    suit: 'swords',
    number: 9,
    keywords: ['anxiety', 'worry', 'fear', 'depression', 'nightmares'],
    uprightMeaning: 'Anxiety, worry, fear, depression, nightmares. Mental anguish.',
    reversedMeaning: 'Inner turmoil, deep-seated fears, secrets, releasing worry.',
    image: '/tarot/cards/nine-of-swords.jpg',
  },
  {
    id: 'ten-of-swords',
    name: 'Ten of Swords',
    suit: 'swords',
    number: 10,
    keywords: ['painful endings', 'deep wounds', 'betrayal', 'loss', 'crisis'],
    uprightMeaning: 'Painful endings, deep wounds, betrayal, loss, crisis. Rock bottom.',
    reversedMeaning: 'Recovery, regeneration, resisting an inevitable end.',
    image: '/tarot/cards/ten-of-swords.jpg',
  },
  {
    id: 'page-of-swords',
    name: 'Page of Swords',
    suit: 'swords',
    number: 11,
    keywords: ['new ideas', 'curiosity', 'thirst for knowledge', 'communication'],
    uprightMeaning: 'New ideas, curiosity, thirst for knowledge, new ways of communicating.',
    reversedMeaning: 'Self-expression, all talk and no action, haphazard action.',
    image: '/tarot/cards/page-of-swords.jpg',
  },
  {
    id: 'knight-of-swords',
    name: 'Knight of Swords',
    suit: 'swords',
    number: 12,
    keywords: ['ambitious', 'action-oriented', 'driven', 'fast thinking'],
    uprightMeaning: 'Ambitious, action-oriented, driven to succeed, fast-thinking.',
    reversedMeaning: 'Restless, unfocused, impulsive, burn-out.',
    image: '/tarot/cards/knight-of-swords.jpg',
  },
  {
    id: 'queen-of-swords',
    name: 'Queen of Swords',
    suit: 'swords',
    number: 13,
    keywords: ['independent', 'unbiased judgement', 'clear boundaries', 'direct communication'],
    uprightMeaning: 'Independent, unbiased judgement, clear boundaries, direct communication.',
    reversedMeaning: 'Overly-emotional, easily influenced, bitchy, cold-hearted.',
    image: '/tarot/cards/queen-of-swords.jpg',
  },
  {
    id: 'king-of-swords',
    name: 'King of Swords',
    suit: 'swords',
    number: 14,
    keywords: ['mental clarity', 'intellectual power', 'authority', 'truth'],
    uprightMeaning: 'Mental clarity, intellectual power, authority, truth. Clear thinking.',
    reversedMeaning: 'Quiet power, inner truth, misuse of power, manipulation.',
    image: '/tarot/cards/king-of-swords.jpg',
  },
]

export const PENTACLES: TarotCard[] = [
  {
    id: 'ace-of-pentacles',
    name: 'Ace of Pentacles',
    suit: 'pentacles',
    number: 1,
    keywords: ['new financial opportunity', 'manifestation', 'abundance'],
    uprightMeaning: 'A new financial or career opportunity, manifestation, abundance.',
    reversedMeaning: 'Lost opportunity, lack of planning, missed chance.',
    image: '/tarot/cards/ace-of-pentacles.jpg',
  },
  {
    id: 'two-of-pentacles',
    name: 'Two of Pentacles',
    suit: 'pentacles',
    number: 2,
    keywords: ['balance', 'adaptability', 'time management', 'prioritisation'],
    uprightMeaning: 'Multiple priorities, time management, prioritisation, adaptability.',
    reversedMeaning: 'Over-committed, disorganisation, reprioritisation.',
    image: '/tarot/cards/two-of-pentacles.jpg',
  },
  {
    id: 'three-of-pentacles',
    name: 'Three of Pentacles',
    suit: 'pentacles',
    number: 3,
    keywords: ['teamwork', 'collaboration', 'learning', 'implementation'],
    uprightMeaning: 'Teamwork, collaboration, learning, implementation. Building something.',
    reversedMeaning: 'Disharmony, misalignment, working alone.',
    image: '/tarot/cards/three-of-pentacles.jpg',
  },
  {
    id: 'four-of-pentacles',
    name: 'Four of Pentacles',
    suit: 'pentacles',
    number: 4,
    keywords: ['saving money', 'security', 'conservatism', 'scarcity'],
    uprightMeaning: 'Saving money, security, conservatism, scarcity, control.',
    reversedMeaning: 'Over-spending, greed, self-protection.',
    image: '/tarot/cards/four-of-pentacles.jpg',
  },
  {
    id: 'five-of-pentacles',
    name: 'Five of Pentacles',
    suit: 'pentacles',
    number: 5,
    keywords: ['financial loss', 'poverty', 'lack mindset', 'isolation'],
    uprightMeaning: 'Financial loss, poverty, lack mindset, isolation, worry.',
    reversedMeaning: 'Recovery from financial loss, spiritual poverty.',
    image: '/tarot/cards/five-of-pentacles.jpg',
  },
  {
    id: 'six-of-pentacles',
    name: 'Six of Pentacles',
    suit: 'pentacles',
    number: 6,
    keywords: ['giving', 'receiving', 'sharing wealth', 'generosity'],
    uprightMeaning: 'Giving, receiving, sharing wealth, generosity, charity.',
    reversedMeaning: 'Self-care, unpaid debts, one-sided charity.',
    image: '/tarot/cards/six-of-pentacles.jpg',
  },
  {
    id: 'seven-of-pentacles',
    name: 'Seven of Pentacles',
    suit: 'pentacles',
    number: 7,
    keywords: ['long-term view', 'sustainable results', 'perseverance', 'investment'],
    uprightMeaning: 'Long-term view, sustainable results, perseverance, investment.',
    reversedMeaning: 'Lack of long-term vision, limited success or reward.',
    image: '/tarot/cards/seven-of-pentacles.jpg',
  },
  {
    id: 'eight-of-pentacles',
    name: 'Eight of Pentacles',
    suit: 'pentacles',
    number: 8,
    keywords: ['apprenticeship', 'repetitive tasks', 'mastery', 'skill development'],
    uprightMeaning: 'Apprenticeship, repetitive tasks, mastery, skill development.',
    reversedMeaning: 'Self-development, perfectionism, misdirected activity.',
    image: '/tarot/cards/eight-of-pentacles.jpg',
  },
  {
    id: 'nine-of-pentacles',
    name: 'Nine of Pentacles',
    suit: 'pentacles',
    number: 9,
    keywords: ['abundance', 'luxury', 'self-sufficiency', 'financial independence'],
    uprightMeaning: 'Abundance, luxury, self-sufficiency, financial independence.',
    reversedMeaning: 'Self-worth, over-investment in work, hustling.',
    image: '/tarot/cards/nine-of-pentacles.jpg',
  },
  {
    id: 'ten-of-pentacles',
    name: 'Ten of Pentacles',
    suit: 'pentacles',
    number: 10,
    keywords: ['wealth', 'financial security', 'family', 'long-term success'],
    uprightMeaning: 'Wealth, financial security, family, long-term success, contribution.',
    reversedMeaning: 'The dark side of wealth, financial failure or loss.',
    image: '/tarot/cards/ten-of-pentacles.jpg',
  },
  {
    id: 'page-of-pentacles',
    name: 'Page of Pentacles',
    suit: 'pentacles',
    number: 11,
    keywords: ['manifestation', 'financial opportunity', 'skill development'],
    uprightMeaning: 'Manifestation, financial opportunity, skill development.',
    reversedMeaning: 'Lack of progress, procrastination, learn from failure.',
    image: '/tarot/cards/page-of-pentacles.jpg',
  },
  {
    id: 'knight-of-pentacles',
    name: 'Knight of Pentacles',
    suit: 'pentacles',
    number: 12,
    keywords: ['hard work', 'productivity', 'routine', 'conservatism'],
    uprightMeaning: 'Hard work, productivity, routine, conservatism. Slow and steady.',
    reversedMeaning: 'Self-discipline, boredom, feeling "stuck", perfectionism.',
    image: '/tarot/cards/knight-of-pentacles.jpg',
  },
  {
    id: 'queen-of-pentacles',
    name: 'Queen of Pentacles',
    suit: 'pentacles',
    number: 13,
    keywords: ['nurturing', 'practical', 'providing financially', 'working parent'],
    uprightMeaning: 'Nurturing, practical, providing financially, a working parent.',
    reversedMeaning: 'Financial independence, self-care, work-home conflict.',
    image: '/tarot/cards/queen-of-pentacles.jpg',
  },
  {
    id: 'king-of-pentacles',
    name: 'King of Pentacles',
    suit: 'pentacles',
    number: 14,
    keywords: ['wealth', 'business', 'leadership', 'security', 'discipline'],
    uprightMeaning: 'Wealth, business, leadership, security, discipline, abundance.',
    reversedMeaning: 'Financially inept, obsessed with wealth, stubborn.',
    image: '/tarot/cards/king-of-pentacles.jpg',
  },
]

// Complete deck combining all cards
export const TAROT_DECK: TarotCard[] = [
  ...MAJOR_ARCANA,
  ...WANDS,
  ...CUPS,
  ...SWORDS,
  ...PENTACLES,
]

// Helper function to get a card by ID
export function getCard(cardId: string): TarotCard | undefined {
  return TAROT_DECK.find(card => card.id === cardId)
}

// Helper function to get random cards from the deck
export function drawRandomCards(count: number): Array<{ card: TarotCard; isReversed: boolean }> {
  const shuffled = [...TAROT_DECK].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count).map(card => ({
    card,
    isReversed: Math.random() > 0.5,
  }))
}
